/*

    MCC_Listtree (c) by kMel, Klaus Melchior
    Registered class of the Magic User Interface.

    AmigaE Interface by Jan Hendrik Schulz
                        schulz_j@informatik.fh-hamburg.de

    Now generated by PrMake (c) kmel

*/


OPT MODULE
OPT EXPORT
OPT PREPROCESS


MODULE 'libraries/mui', 'utility/tagitem'


/*** MUI Defines ***/

#define MUIC_Listtree 'Listtree.mcc'
#define MUIC_ListtreeP 'Listtree.mcp'
#define ListtreeObject Mui_NewObjectA(MUIC_Listtree,[TAG_IGNORE,0


/*** Methods ***/

CONST MUIM_Listtree_Active               = $8002000f
CONST MUIM_Listtree_Clear                = $8002006d
CONST MUIM_Listtree_Close                = $8002001f
CONST MUIM_Listtree_Data                 = $80020023
CONST MUIM_Listtree_DoubleClick          = $8002002a
CONST MUIM_Listtree_Exchange             = $80020008
CONST MUIM_Listtree_FindName             = $8002003c
CONST MUIM_Listtree_GetEntry             = $8002002b
CONST MUIM_Listtree_GetNr                = $8002000e
CONST MUIM_Listtree_Insert               = $80020011
CONST MUIM_Listtree_Move                 = $80020009
CONST MUIM_Listtree_Open                 = $8002001e
CONST MUIM_Listtree_Remove               = $80020012
CONST MUIM_Listtree_Rename               = $8002000c
CONST MUIM_Listtree_SetDropMark          = $8002004c
CONST MUIM_Listtree_TestPos              = $8002004b

/*** Method structs ***/

OBJECT muip_listtree_active
   methodid:LONG
   position:LONG
ENDOBJECT

OBJECT muip_listtree_clear
   methodid:LONG
ENDOBJECT

OBJECT muip_listtree_close
   methodid:LONG
   listnode:LONG
   treenode:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_data
   methodid:LONG
   id:LONG
   set:LONG
ENDOBJECT

OBJECT muip_listtree_doubleclick
   methodid:LONG
ENDOBJECT

OBJECT muip_listtree_exchange
   methodid:LONG
   listnode1:LONG
   treenode1:LONG
   listnode2:LONG
   treenode2:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_findname
   methodid:LONG
   listnode:LONG
   name:PTR TO CHAR
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_getentry
   methodid:LONG
   node:LONG
   position:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_getnr
   methodid:LONG
   treenode:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_insert
   methodid:LONG
   name:PTR TO CHAR
   user:LONG
   listnode:LONG
   prevnode:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_move
   methodid:LONG
   oldlistnode:LONG
   oldtreenode:LONG
   newlistnode:LONG
   newtreenode:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_open
   methodid:LONG
   listnode:LONG
   treenode:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_remove
   methodid:LONG
   listnode:LONG
   treenode:LONG
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_rename
   methodid:LONG
   treenode:LONG
   newname:PTR TO CHAR
   flags:LONG
ENDOBJECT

OBJECT muip_listtree_setdropmark
   methodid:LONG
   entry:LONG
   values:LONG
ENDOBJECT

OBJECT muip_listtree_testpos
   methodid:LONG
   x:LONG
   y:LONG
   result:LONG
ENDOBJECT


/*** Special method values ***/

CONST MUIV_Listtree_Close_ListNode_Root        =   0
CONST MUIV_Listtree_Close_ListNode_Parent      =  -1
CONST MUIV_Listtree_Close_ListNode_Active      =  -2

CONST MUIV_Listtree_Close_TreeNode_Head        =   0
CONST MUIV_Listtree_Close_TreeNode_Tail        =  -1
CONST MUIV_Listtree_Close_TreeNode_Active      =  -2
CONST MUIV_Listtree_Close_TreeNode_All         =  -3

CONST MUIV_Listtree_Data_MemPool               =   1
CONST MUIV_Listtree_Data_VersInfo              =   2
CONST MUIV_Listtree_Data_Sample                =   3

CONST MUIV_Listtree_Exchange_ListNode1_Root    =   0
CONST MUIV_Listtree_Exchange_ListNode1_Active  =  -2

CONST MUIV_Listtree_Exchange_TreeNode1_Head    =   0
CONST MUIV_Listtree_Exchange_TreeNode1_Tail    =  -1
CONST MUIV_Listtree_Exchange_TreeNode1_Active  =  -2

CONST MUIV_Listtree_Exchange_ListNode2_Root    =   0
CONST MUIV_Listtree_Exchange_ListNode2_Active  =  -2

CONST MUIV_Listtree_Exchange_TreeNode2_Head    =   0
CONST MUIV_Listtree_Exchange_TreeNode2_Tail    =  -1
CONST MUIV_Listtree_Exchange_TreeNode2_Active  =  -2
CONST MUIV_Listtree_Exchange_TreeNode2_Up      =  -5
CONST MUIV_Listtree_Exchange_TreeNode2_Down    =  -6

CONST MUIV_Listtree_FindName_ListNode_Root     =   0
CONST MUIV_Listtree_FindName_ListNode_Active   =  -2

CONST MUIV_Listtree_GetEntry_ListNode_Root     =   0
CONST MUIV_Listtree_GetEntry_ListNode_Active   =  -2

CONST MUIV_Listtree_GetEntry_Position_Head     =   0
CONST MUIV_Listtree_GetEntry_Position_Tail     =  -1
CONST MUIV_Listtree_GetEntry_Position_Active   =  -2
CONST MUIV_Listtree_GetEntry_Position_Next     =  -3
CONST MUIV_Listtree_GetEntry_Position_Previous =  -4
CONST MUIV_Listtree_GetEntry_Position_Parent   =  -5
CONST MUIV_Listtree_GetEntry_Position_Root     = -15

CONST MUIV_Listtree_GetNr_TreeNode_Active      =  -2

CONST MUIV_Listtree_Insert_ListNode_Root       =   0
CONST MUIV_Listtree_Insert_ListNode_Active     =  -2

CONST MUIV_Listtree_Insert_PrevNode_Head       =   0
CONST MUIV_Listtree_Insert_PrevNode_Tail       =  -1
CONST MUIV_Listtree_Insert_PrevNode_Active     =  -2
CONST MUIV_Listtree_Insert_PrevNode_Sorted     =  -4

CONST MUIV_Listtree_Move_OldListNode_Root      =   0
CONST MUIV_Listtree_Move_OldListNode_Active    =  -2

CONST MUIV_Listtree_Move_OldTreeNode_Head      =   0
CONST MUIV_Listtree_Move_OldTreeNode_Tail      =  -1
CONST MUIV_Listtree_Move_OldTreeNode_Active    =  -2

CONST MUIV_Listtree_Move_NewListNode_Root      =   0
CONST MUIV_Listtree_Move_NewListNode_Active    =  -2

CONST MUIV_Listtree_Move_NewTreeNode_Head      =   0
CONST MUIV_Listtree_Move_NewTreeNode_Tail      =  -1
CONST MUIV_Listtree_Move_NewTreeNode_Active    =  -2
CONST MUIV_Listtree_Move_NewTreeNode_Sorted    =  -4

CONST MUIV_Listtree_Open_ListNode_Root         =   0
CONST MUIV_Listtree_Open_ListNode_Parent       =  -1
CONST MUIV_Listtree_Open_ListNode_Active       =  -2
CONST MUIV_Listtree_Open_TreeNode_Head         =   0
CONST MUIV_Listtree_Open_TreeNode_Tail         =  -1
CONST MUIV_Listtree_Open_TreeNode_Active       =  -2
CONST MUIV_Listtree_Open_TreeNode_All          =  -3

CONST MUIV_Listtree_Remove_ListNode_Root       =   0
CONST MUIV_Listtree_Remove_ListNode_Active     =  -2
CONST MUIV_Listtree_Remove_TreeNode_Head       =   0
CONST MUIV_Listtree_Remove_TreeNode_Tail       =  -1
CONST MUIV_Listtree_Remove_TreeNode_Active     =  -2
CONST MUIV_Listtree_Remove_TreeNode_All        =  -3

CONST MUIV_Listtree_Rename_TreeNode_Active     =  -2

CONST MUIV_Listtree_SetDropMark_Entry_None     =  -1

CONST MUIV_Listtree_SetDropMark_Values_None    =   0
CONST MUIV_Listtree_SetDropMark_Values_Above   =   1
CONST MUIV_Listtree_SetDropMark_Values_Below   =   2
CONST MUIV_Listtree_SetDropMark_Values_Onto    =   3
CONST MUIV_Listtree_SetDropMark_Values_Sorted  =   4

CONST MUIV_Listtree_TestPos_Result_Flags_None  =   0
CONST MUIV_Listtree_TestPos_Result_Flags_Above =   1
CONST MUIV_Listtree_TestPos_Result_Flags_Below =   2
CONST MUIV_Listtree_TestPos_Result_Flags_Onto  =   3
CONST MUIV_Listtree_TestPos_Result_Flags_Sorted =   4


/*** Special method flags ***/

CONST MUIV_Listtree_Close_Flags_Nr             = $8000
CONST MUIV_Listtree_Close_Flags_Visible        = $4000

CONST MUIV_Listtree_FindName_Flags_SameLevel   = $8000
CONST MUIV_Listtree_FindName_Flags_Visible     = $4000

CONST MUIV_Listtree_GetEntry_Flags_SameLevel   = $8000
CONST MUIV_Listtree_GetEntry_Flags_Visible     = $4000

CONST MUIV_Listtree_GetNr_Flags_ListEmpty      = $1000
CONST MUIV_Listtree_GetNr_Flags_CountList      = $2000
CONST MUIV_Listtree_GetNr_Flags_CountLevel     = $4000
CONST MUIV_Listtree_GetNr_Flags_CountAll       = $8000

CONST MUIV_Listtree_Insert_Flags_Nr            = $8000
CONST MUIV_Listtree_Insert_Flags_Visible       = $4000
CONST MUIV_Listtree_Insert_Flags_Active        = $2000
CONST MUIV_Listtree_Insert_Flags_NextNode      = $1000

CONST MUIV_Listtree_Move_Flags_Nr              = $8000
CONST MUIV_Listtree_Move_Flags_Visible         = $4000

CONST MUIV_Listtree_Open_Flags_Nr              = $8000
CONST MUIV_Listtree_Open_Flags_Visible         = $4000

CONST MUIV_Listtree_Remove_Flags_Nr            = $8000
CONST MUIV_Listtree_Remove_Flags_Visible       = $4000

CONST MUIV_Listtree_Rename_Flags_User          = $0100
CONST MUIV_Listtree_Rename_Flags_NoRefresh     = $0200


/*** Attributes ***/

CONST MUIA_Listtree_Active               = $80020020
CONST MUIA_Listtree_CloseHook            = $80020033
CONST MUIA_Listtree_ConstructHook        = $80020016
CONST MUIA_Listtree_DestructHook         = $80020017
CONST MUIA_Listtree_DisplayHook          = $80020018
CONST MUIA_Listtree_DisplayOpened        = $8002002e
CONST MUIA_Listtree_DoubleClick          = $8002000d
CONST MUIA_Listtree_DragDropSort         = $80020031
CONST MUIA_Listtree_DuplicateNodeName    = $8002003d
CONST MUIA_Listtree_EmptyNodes           = $80020030
CONST MUIA_Listtree_EntryChanged         = $8002006a
CONST MUIA_Listtree_Format               = $80020014
CONST MUIA_Listtree_ImageSpecDown        = $8002001b
CONST MUIA_Listtree_ImageSpecRight       = $8002001a
CONST MUIA_Listtree_OpenHook             = $80020032
CONST MUIA_Listtree_PenSpecLines         = $8002002f
CONST MUIA_Listtree_Quiet                = $8002000a
CONST MUIA_Listtree_Refresh              = $8002001c
CONST MUIA_Listtree_RememberStatus       = $8002001d
CONST MUIA_Listtree_SortHook             = $80020010
CONST MUIA_Listtree_Space                = $8002002d
CONST MUIA_Listtree_Style                = $8002002c
CONST MUIA_Listtree_Title                = $80020015
CONST MUIA_Listtree_TreeColumn           = $80020013

/*** Special attribute values ***/

CONST MUIV_Listtree_Active_Off           =   0

CONST MUIV_Listtree_ConstructHook_String =  -1

CONST MUIV_Listtree_DestructHook_String  =  -1

CONST MUIV_Listtree_DisplayHook_Default  =  -1

CONST MUIV_Listtree_DoubleClick_Off      =  -1
CONST MUIV_Listtree_DoubleClick_All      =  -2
CONST MUIV_Listtree_DoubleClick_Tree     =  -3

CONST MUIV_Listtree_Refresh_Flag         = $8000

CONST MUIV_Listtree_SortHook_Head        =   0
CONST MUIV_Listtree_SortHook_Tail        =  -1
CONST MUIV_Listtree_SortHook_LeavesTop   =  -2
CONST MUIV_Listtree_SortHook_LeavesMixed =  -3
CONST MUIV_Listtree_SortHook_LeavesBottom =  -4


/*** Structures, Flags & Values ***/

OBJECT muis_listtree_treenode
   tn_Private1:LONG
   tn_Private2:LONG
   tn_Name:PTR TO CHAR
   tn_Flags:INT
   tn_User:LONG
ENDOBJECT

OBJECT muis_listtree_testpos_result
   tpr_TreeNode:LONG
   tpr_Flags:INT
   tpr_ListEntry:LONG
   tpr_ListFlags:INT
ENDOBJECT


CONST TNF_OPEN   = $0001
CONST TNF_LIST   = $0002
CONST TNF_FROZEN = $0004
CONST TNF_NOSIGN = $0008



/* PrMake.rexx 0.10 (16.2.1996) Copyright 1995 kmel, Klaus Melchior */

